### ISSUE TITLE
Native build fails on Linux

### ISSUE THREAD

**Issue by Phantop** [ArchLeaders/Cead#3]
As the title says, recursively cloning and trying to build the native portion of the library fails on my Arch Linux system.

I do so by making a `build` directory in `native`, and running `cmake -G Ninja .. && ninja -C .`, which fails.

The error is attached as a file.

[error.txt](https://github.com/ArchLeaders/Cead/files/12232723/error.txt)

**Comment by ArchLeaders** [comment]
What's your gcc version? Abseil only builds on the later versions of gcc, so make sure that's updated.

Also I should mention that this library is now depreciated in favor of [cs-oead](https://github.com/EPD-Libraries/cs-oead)

**Comment by Phantop** [comment]
I'm on GCC 13.1.1, Clang 15.0.7. Neither works.

I am aware it's deprecated, though I'm currently working on porting the [TotkRandomizer](https://github.com/MelonSpeedruns/TotkRandomizer) to Linux, which uses this library, and Cead seems to be a major blocker in doing so.

I have managed to compile it sucessfully by pulling all the submodules to their latest commits (no doubt breaking stuff in the process but... it built?) and actual use of the library seems hampered.

A line like:
```C#
Byml byaml = Byml.FromBinary(myByteArray);
```
terminates the entire program:
```
terminate called after throwing an instance of 'oead::InvalidDataError'
  what():  Unexpected version
```

Considering I'm mostly just buggering around with this, I have no clue what I'm doing and how to even *begin* to approach getting this working 😅. Help is appreciated, though understandable if you don't want to for a deprecated library.

**Comment by ArchLeaders** [comment]
That error usually indicates the byml you're opening is invalid. Is it by chance compressed with zstd still?

**Comment by Phantop** [comment]
That is... possible? But unlikely. I can confirm that the code I'm using works with the compiled Windows Cead.dll found [here](https://github.com/MelonSpeedruns/TotkRandomizer/blob/main/Cead.dll) in Wine. I'm using a modified version of that repo, and I haven't touched any of the compression or HashTable code used, so I don't really know where the discrepency would be.

**Comment by ArchLeaders** [comment]
Might not be what you're looking for as far as maintainability, but have you tried using the linux build from the [workflows](https://github.com/ArchLeaders/Cead/actions/runs/5730357237)?

I know that build works on linux, so if that doesn't work then it's likely an issue with your byml file somewhere/somehow.

**Comment by Phantop** [comment]
Using the existing dll file gives me this error. My own dll gives me the error I've said above, as does including Cead as a ProjectReference.
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library '/tmp/Cead-1.0.0.0/Cead.lib' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/tmp/Cead-1.0.0.0/Cead.lib: invalid ELF header

   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at Cead.Interop.DllManager.LoadCead() in D:\a\Cead\Cead\src\Interop\DllManager.cs:line 48
   at TotkRandomizer.Program.Main(String[] args) in /home/glados/Downloads/TotkRandomizer/Program.cs:line 16
fish: Job 1, 'bin/Debug/net7.0/TotkRandomizer…' terminated by signal SIGABRT (Abort)
```

**Comment by ArchLeaders** [comment]
Yeah the included dll contains a windows native assembly, so it won't work on linux. But the `Cead.so` in the workflows should work fine (assuming it's not the byml file, which I suspect).

**Comment by Phantop** [comment]
Hmm yeah it's still happening with that one... I really don't know what's up with this. This code *does* work through Wine with the same files, so I suppose it could be something else within it that doesn't work on Linux. I suppose I could take some time to do some additional testing on this elsewhere, then.

**Comment by Phantop** [comment]
Some additional testing does appear to indicate that Byml reading just doesn't work for me. 

```c#
using Cead;
using Cead.Interop;

DllManager.LoadCead();
Span<byte> data = File.ReadAllBytes(@"A-7_Dynamic.bcett.byml");
Byml byaml = Byml.FromBinary(data);
```

gives the same error. The byml file is valid and opens in NX-Editor.

**Comment by Phantop** [comment]
...I just noticed that there's another repo for this on TotkMods, which doesn't have this issue...

Really sorry for wasting your time my god. Thanks for your assistance either way!

**Comment by ArchLeaders** [comment]
No worries, glad you found the issue 👍
